import { _registerBuiltin, DEFAULT_TIMESTAMP_FORMAT } from './Variables';

/**
 * Built-in variables. Imported from `extension.ts` at activation so the
 * registry is populated before any panel tries to enumerate variables.
 *
 * Currently registered:
 *  - timestamp: current time, formatted with the user-configurable
 *    `tcpClient.variables.timestampFormat` setting (default ISO 8601),
 *    or an inline pipe format (`{{timestamp|FMT}}`). Always present,
 *    not deletable from the UI.
 *  - seq: per-session counter starting at 1. Value is computed at
 *    substitution time from the `state.seq` arg the panel passes in
 *    (`substitute()` warns and falls back to 1 if no state). The `value`
 *    field below is a placeholder; the real number lives in panel state.
 *  - uuid: fresh RFC 4122 v4 UUID per substitution call, generated by
 *    `crypto.randomUUID()`. The `value` field below is a placeholder.
 *
 * The `format` field on `timestamp` is the seed default;
 * `formatTimestamp` reads the live setting at substitution time, so
 * user-configured formats take precedence (or the pipe format on the
 * specific reference). We seed it here so the registry has a usable
 * entry even when the test runner has not set the setting (e.g.
 * headless unit tests that don't import extension.ts).
 */
_registerBuiltin({
  name: 'timestamp',
  value: '',
  format: DEFAULT_TIMESTAMP_FORMAT,
  builtin: true,
});
_registerBuiltin({ name: 'seq',  value: '', builtin: true });
_registerBuiltin({ name: 'uuid', value: '', builtin: true });
